// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobConclusion } from "./JobConclusion";
import type { RunnerInfo } from "./RunnerInfo";
import type { Step } from "./Step";

/**
 * Action that occurred on a job.
 */
export type JobEvent = { "type": "Queued", "data": { 
/**
 * Runner labels requested by this job.
 */
labels: Array<string>, 
/**
 * Current step snapshot.
 */
steps: Array<Step>, } } | { "type": "Waiting", "data": { 
/**
 * Runner labels requested by the job.
 */
labels: Array<string>, 
/**
 * Steps defined in the job at the time of the event.
 */
steps: Array<Step>, } } | { "type": "InProgress", "data": { 
/**
 * Runner assigned to the job. `None` when GitHub fires `in_progress`
 * before runner assignment is complete.
 */
runner: RunnerInfo | null, 
/**
 * Runner labels.
 */
labels: Array<string>, 
/**
 * Current step snapshot.
 */
steps: Array<Step>, } } | { "type": "Completed", "data": { 
/**
 * The conclusion of the job.
 */
conclusion: JobConclusion, 
/**
 * Runner that executed the job, if known.
 */
runner: RunnerInfo | null, 
/**
 * Runner labels.
 */
labels: Array<string>, 
/**
 * Final step snapshot.
 */
steps: Array<Step>, } };
