// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunEvent } from "./RunEvent";
import type { RunId } from "./RunId";

/**
 * Full run event data for state store ingestion.
 *
 * Carries all fields needed to create or update a `WorkflowRun`.
 */
export type RunEventEnvelope = { 
/**
 * Unique identifier for the run.
 */
runId: RunId, 
/**
 * Organization name.
 */
org: string, 
/**
 * Repository name.
 */
repo: string, 
/**
 * Workflow name from the `workflow` object. `None` when GitHub sends
 * `workflow: null` (common on `in_progress` and `completed` events).
 */
workflowName: string | null, 
/**
 * Workflow file path. `None` when GitHub sends `workflow: null`.
 */
workflowPath: string | null, 
/**
 * Branch name, if applicable.
 */
branch: string | null, 
/**
 * Head commit SHA.
 */
headSha: string, 
/**
 * Head commit message.
 */
commitMessage: string | null, 
/**
 * Event that triggered the run (e.g., `push`, `pull_request`).
 */
triggerEvent: string, 
/**
 * Display title for the run.
 */
displayTitle: string, 
/**
 * URL to the run on GitHub.
 */
htmlUrl: string, 
/**
 * When the run was created.
 */
createdAt: string, 
/**
 * When the run started executing.
 */
runStartedAt: string | null, 
/**
 * When the run was last updated.
 */
updatedAt: string, 
/**
 * The action that occurred.
 */
action: RunEvent, };
