// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunConclusion } from "./RunConclusion";

/**
 * Action that occurred on a workflow run.
 */
export type RunEvent = { "type": "Requested" } | { "type": "InProgress" } | { "type": "Completed", "data": { 
/**
 * The conclusion of the run.
 */
conclusion: RunConclusion, } };
