// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobEventEnvelope } from "./JobEventEnvelope";
import type { RunEventEnvelope } from "./RunEventEnvelope";

/**
 * A parsed webhook event carrying a domain event envelope.
 */
export type WebhookEvent = { "type": "Run", "data": RunEventEnvelope } | { "type": "Job", "data": JobEventEnvelope };
