apiVersion: v1
entries:
  atc:
  - apiVersion: v2
    appVersion: 0.5.0
    created: "2026-07-21T11:55:46.384250981Z"
    description: Real-time GitHub Actions dashboard
    digest: 23c280b9398b78d860f507673f13a26ed8c11e9d335afbd0f2e17ee0aff28a4c
    kubeVersion: '>=1.32.0-0'
    maintainers:
    - email: brajkovic@coderinserepeat.com
      name: Bojan Rajkovic
    name: atc
    type: application
    urls:
    - https://github.com/bojanrajkovic/atc/releases/download/atc-0.5.0/atc-0.5.0.tgz
    version: 0.5.0
  - apiVersion: v2
    appVersion: 0.4.1
    created: "2026-07-08T00:33:42.855910685Z"
    description: Real-time GitHub Actions dashboard
    digest: 998481d73214d0cfc499b77eda6ef61dd19b677873069cfac01429fdea6150cc
    kubeVersion: '>=1.32.0-0'
    maintainers:
    - email: brajkovic@coderinserepeat.com
      name: Bojan Rajkovic
    name: atc
    type: application
    urls:
    - https://github.com/bojanrajkovic/atc/releases/download/atc-0.4.1/atc-0.4.1.tgz
    version: 0.4.1
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2026-07-07T23:28:26.025158956Z"
    description: Real-time GitHub Actions dashboard
    digest: 8a41ce81c2e1cf7a7d80a238741d92cdf6151a9289758703c588c1a55611f340
    kubeVersion: '>=1.32.0-0'
    maintainers:
    - email: brajkovic@coderinserepeat.com
      name: Bojan Rajkovic
    name: atc
    type: application
    urls:
    - https://github.com/bojanrajkovic/atc/releases/download/atc-0.4.0/atc-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: 0.3.0
    created: "2026-07-06T00:20:26.54462172Z"
    description: Real-time GitHub Actions dashboard
    digest: 4bec4c821dda6731e58513e6e46806f7f6e00f90d9cf70ac56cf5579fe97f85e
    kubeVersion: '>=1.32.0-0'
    maintainers:
    - email: brajkovic@coderinserepeat.com
      name: Bojan Rajkovic
    name: atc
    type: application
    urls:
    - https://github.com/bojanrajkovic/atc/releases/download/atc-0.3.0/atc-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 0.2.0
    created: "2026-06-04T14:15:53.949083488Z"
    description: Real-time GitHub Actions dashboard
    digest: e822809f63a02ffe5fa6ba949dedec0f6daf2f47bb005e364ee363d082674f59
    kubeVersion: '>=1.32.0-0'
    maintainers:
    - email: brajkovic@coderinserepeat.com
      name: Bojan Rajkovic
    name: atc
    type: application
    urls:
    - https://github.com/bojanrajkovic/atc/releases/download/atc-0.2.0/atc-0.2.0.tgz
    version: 0.2.0
generated: "2026-07-21T11:55:46.384274364Z"
