// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunConclusion } from "./RunConclusion";
import type { RunId } from "./RunId";
import type { RunStatus } from "./RunStatus";

/**
 * A workflow run in the ATC domain model.
 *
 * Top-level container that groups related jobs. Created and updated
 * by `RunEvent`s (Phase 2).
 */
export type WorkflowRun = { 
/**
 * Unique identifier for this run.
 */
id: RunId, 
/**
 * GitHub organization or user name.
 */
org: string, 
/**
 * Repository name.
 */
repo: string, 
/**
 * Name of the workflow. `None` until an event supplies it; once set, preserved via `.or()` across subsequent events.
 */
workflowName: string | null, 
/**
 * Path to the workflow file. `None` until an event supplies it; once set, preserved via `.or()` across subsequent events.
 */
workflowPath: string | null, 
/**
 * Branch that triggered the run, if applicable.
 */
branch: string | null, 
/**
 * Git commit SHA at the head of the run.
 */
headSha: string, 
/**
 * Commit message, if available.
 */
commitMessage: string | null, 
/**
 * Event that triggered the run (e.g., `push`, `pull_request`).
 */
event: string, 
/**
 * Human-readable display title for the run.
 */
displayTitle: string, 
/**
 * Current lifecycle status.
 */
status: RunStatus, 
/**
 * Final conclusion, populated when status is `Completed`.
 */
conclusion: RunConclusion | null, 
/**
 * URL to the run on GitHub.
 */
htmlUrl: string, 
/**
 * When the run was created.
 */
createdAt: string, 
/**
 * When the run started executing, if it has started.
 */
runStartedAt: string | null, 
/**
 * When the run was last updated.
 */
updatedAt: string, };
