// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobConclusion } from "./JobConclusion";
import type { JobId } from "./JobId";
import type { JobStatus } from "./JobStatus";
import type { RunId } from "./RunId";
import type { RunnerInfo } from "./RunnerInfo";
import type { Step } from "./Step";

/**
 * A job within a workflow run.
 *
 * Created and updated by `JobEvent`s (Phase 2). Steps use snapshot
 * semantics — the entire `Vec<Step>` is replaced on each event.
 */
export type Job = { 
/**
 * Unique identifier for this job.
 */
id: JobId, 
/**
 * Display name of the job.
 */
name: string, 
/**
 * Back-reference to the parent workflow run.
 */
runId: RunId, 
/**
 * Current lifecycle status.
 */
status: JobStatus, 
/**
 * Final conclusion, populated when status is `Completed`.
 */
conclusion: JobConclusion | null, 
/**
 * Runner assigned to this job, populated when a runner picks it up.
 */
runner: RunnerInfo | null, 
/**
 * Runner labels this job requires.
 */
labels: Array<string>, 
/**
 * Steps within this job, ordered by step number.
 */
steps: Array<Step>, 
/**
 * When the job was created.
 */
createdAt: string, 
/**
 * When the job started executing.
 */
startedAt: string | null, 
/**
 * When the job finished executing.
 */
completedAt: string | null, };
