// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Conclusion of a completed job.
 */
export type JobConclusion = "Success" | "Failure" | "Cancelled" | "TimedOut" | "ActionRequired" | "Stale" | "Neutral" | "Skipped";
