// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobEvent } from "./JobEvent";
import type { JobId } from "./JobId";
import type { RunId } from "./RunId";

/**
 * Full job event data for state store ingestion.
 *
 * Carries all fields needed to create or update a `Job`.
 */
export type JobEventEnvelope = { 
/**
 * Unique identifier for the job.
 */
jobId: JobId, 
/**
 * Back-reference to the parent run.
 */
runId: RunId, 
/**
 * Organization name.
 */
org: string, 
/**
 * Repository name.
 */
repo: string, 
/**
 * Job name.
 */
name: string, 
/**
 * When the job was created.
 */
createdAt: string, 
/**
 * When the job started executing.
 */
startedAt: string | null, 
/**
 * When the job finished executing.
 */
completedAt: string | null, 
/**
 * The action that occurred.
 */
action: JobEvent, };
