{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "atc.fullname" . }}
  labels:
    {{- include "atc.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "atc.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- if hasKey .Values.networkPolicy "ingress" }}
    - Ingress
    {{- end }}
    {{- if hasKey .Values.networkPolicy "egress" }}
    - Egress
    {{- end }}
  {{- if hasKey .Values.networkPolicy "ingress" }}
  {{- if empty .Values.networkPolicy.ingress }}
  ingress: []
  {{- else }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if hasKey .Values.networkPolicy "egress" }}
  {{- if empty .Values.networkPolicy.egress }}
  egress: []
  {{- else }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
